# Generated by Django 5.2.11 on 2026-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_employee_contact_no_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Question', 'Question'), ('Bugs', 'Bugs'), ('Problems', 'Problems'), ('Incident', 'Incident'), ('Custom Integration', 'Custom Integration'), ('Login creation', 'Login creation')], default='Question', max_length=50),
        ),
    ]
